CXX		= g++-4.8
CXXFLAGS	= -std=c++11 -ggdb
EXECUTABLE  = TestPhase1
EXTENSION   = cpp
SOURCES	 = TestPhase1.cpp ../src/DFA.cpp ../src/eNFA.cpp readInput.cpp ini_configuration.cpp

all:
	$(CXX) $(CXXFLAGS) $(SOURCES) -o $(EXECUTABLE)
